@startuml

title Loading ServerSide Blazor

skinparam componentStyle uml2
autonumber "<b>[0]"

actor Browser
control "Blazor Loader" as Loader
entity "ServerSide Blazor" as BlazorServerSide

Browser -> Loader : Execute
Loader -> BlazorServerSide : Activate
activate BlazorServerSide
|||

@enduml
