@startuml

title Case: WebAssembly not supported

skinparam componentStyle uml2
left to right direction

package "Server" {

    cloud "Blazor" {
        component "Blazor Components" as BlazorComponents
    }

    package "Back-End" as BackEnd {
        component "WebHost" as Host
    }

}

package "Browser" {
    component "HTML Page" as Html
    component "Blazor Loader\n(JavaScript)" as Loader
    component "ServerSide Blazor" as BlazorServer
}

Host .> Html : Web Response
Loader <-- Html

Loader ..> BlazorServer
BlazorServer <.[#blue].> BlazorComponents : <color blue>WebSockets</color>

@enduml
