@startuml

title Case: WebAssembly not supported
left to right direction

skinparam componentStyle uml2
skinparam backgroundColor WhiteSmoke

package "Server" {

    package "Blazor" {
        component "Blazor Components" as BlazorComponents
    }

    package "Back-End" as BackEnd {
        component "WebHost" as Host
    }

}

package "Browser" as FrontEnd {

    component "HTML Page" as Html
    component "Blazor Loader\n(JavaScript)" as Loader
    component "ServerSide Blazor" as BlazorServer

}

Host .> Html : Web Response
Loader <-- Html

Loader ..> BlazorServer : Load
BlazorServer <.[#blue].> BlazorComponents : <color blue>WebSocket</color>

@enduml
